/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GestionComponent: typeof import('./components/GestionComponent.vue')['default']
    InicioComponent: typeof import('./components/InicioComponent.vue')['default']
    LoginComponent: typeof import('./components/LoginComponent.vue')['default']
    LogoComponent: typeof import('./components/LogoComponent.vue')['default']
    MenuComponent: typeof import('./components/menu/MenuComponent.vue')['default']
    ProductoComponent: typeof import('./components/productoComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
