/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/ClienteView': RouteRecordInfo<'/ClienteView', '/ClienteView', Record<never, never>, Record<never, never>>,
    '/CompraView': RouteRecordInfo<'/CompraView', '/CompraView', Record<never, never>, Record<never, never>>,
    '/GestionView': RouteRecordInfo<'/GestionView', '/GestionView', Record<never, never>, Record<never, never>>,
    '/InicioView': RouteRecordInfo<'/InicioView', '/InicioView', Record<never, never>, Record<never, never>>,
    '/InventarioView': RouteRecordInfo<'/InventarioView', '/InventarioView', Record<never, never>, Record<never, never>>,
    '/LoginView': RouteRecordInfo<'/LoginView', '/LoginView', Record<never, never>, Record<never, never>>,
    '/ProductoView': RouteRecordInfo<'/ProductoView', '/ProductoView', Record<never, never>, Record<never, never>>,
    '/UsuariosView': RouteRecordInfo<'/UsuariosView', '/UsuariosView', Record<never, never>, Record<never, never>>,
  }
}
